<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="pcch-divyag" name="zf.test.ZFAddMultipleGatewayTest" tests="7" failures="2" timestamp="29 Mar 2019 15:36:01 GMT" time="1113.655" errors="0">
  <testcase name="Tc06AddMultipleGatewayWithUserInterfaceValidation" time="95.943" classname="zf.test.ZFAddMultipleGatewayTest"/>
  <testcase name="Tc02AddMultipleGatewayWithExistingEnrollmentGroup" time="102.658" classname="zf.test.ZFAddMultipleGatewayTest"/>
  <testcase name="Tc01AddMultipleGatewayWithNewEnrollmentGroupWithRootUploadCertificate" time="104.409" classname="zf.test.ZFAddMultipleGatewayTest">
    <failure type="java.lang.AssertionError" message="Expected value is : SUCCESS      Actual value is : Failed">
      <![CDATA[java.lang.AssertionError: Expected value is : SUCCESS      Actual value is : Failed
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.compareText(ExtentReport.java:156)
at zf.pages.ZFAddMultipleGatewayPage.verifyToastermessage(ZFAddMultipleGatewayPage.java:265)
at zf.pages.ZFAddMultipleGatewayPage.addMultipleGatewayNewRoot(ZFAddMultipleGatewayPage.java:96)
at zf.test.ZFAddMultipleGatewayTest.Tc01AddMultipleGatewayWithNewEnrollmentGroupWithRootUploadCertificate(ZFAddMultipleGatewayTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Tc01AddMultipleGatewayWithNewEnrollmentGroupWithRootUploadCertificate -->
  <testcase name="Tc06AddMultipleGatewayWithLookAndFeelValidation" time="354.399" classname="zf.test.ZFAddMultipleGatewayTest"/>
  <testcase name="Tc04AddMultipleGatewayWithNewEnrollmentGroupWithoutMandatoryFields" time="145.204" classname="zf.test.ZFAddMultipleGatewayTest"/>
  <testcase name="Tc03AddMultipleGatewayWithNewEnrollmentGroupWithIntermediateUploadCertificate" time="105.623" classname="zf.test.ZFAddMultipleGatewayTest">
    <failure type="java.lang.AssertionError" message="Expected value is : SUCCESS      Actual value is : Failed">
      <![CDATA[java.lang.AssertionError: Expected value is : SUCCESS      Actual value is : Failed
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.compareText(ExtentReport.java:156)
at zf.pages.ZFAddMultipleGatewayPage.verifyToastermessage(ZFAddMultipleGatewayPage.java:265)
at zf.pages.ZFAddMultipleGatewayPage.addMultipleGatewayNewIntermediate(ZFAddMultipleGatewayPage.java:139)
at zf.test.ZFAddMultipleGatewayTest.Tc03AddMultipleGatewayWithNewEnrollmentGroupWithIntermediateUploadCertificate(ZFAddMultipleGatewayTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Tc03AddMultipleGatewayWithNewEnrollmentGroupWithIntermediateUploadCertificate -->
  <testcase name="Tc05AddMultipleGatewayWithInvalidDetails" time="205.419" classname="zf.test.ZFAddMultipleGatewayTest"/>
</testsuite> <!-- zf.test.ZFAddMultipleGatewayTest -->
