<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="pcch-divyag" name="zf.test.ZFAssetTest" tests="12" failures="7" timestamp="28 Mar 2019 11:15:13 GMT" time="2264.042" errors="0">
  <testcase name="TC21SortAssetsInAssetsHomepage" time="83.519" classname="zf.test.ZFAssetTest">
    <failure type="java.lang.AssertionError" message="TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - Business Unit">
      <![CDATA[java.lang.AssertionError: TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - Business Unit
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.elementCatch(ExtentReport.java:258)
at framework.ElementManager.elementClick(ElementManager.java:63)
at zf.pages.ZFAssetPage.assetSortingDropDownNavigation(ZFAssetPage.java:865)
at zf.pages.ZFAssetPage.SortAssetsInAssetsHomepage(ZFAssetPage.java:854)
at zf.test.ZFAssetTest.TC21SortAssetsInAssetsHomepage(ZFAssetTest.java:139)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC21SortAssetsInAssetsHomepage -->
  <testcase name="TC10CreateAssetstWithAllAutopopulatedMetadataKeys" time="227.857" classname="zf.test.ZFAssetTest"/>
  <testcase name="TC15ExecuteActionWithoutParamater" time="258.564" classname="zf.test.ZFAssetTest">
    <failure type="java.lang.AssertionError" message="TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - Actions">
      <![CDATA[java.lang.AssertionError: TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - Actions
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.elementCatch(ExtentReport.java:258)
at framework.ElementManager.elementClick(ElementManager.java:63)
at zf.pages.ZFAssetPage.executeActionWithoutParamater(ZFAssetPage.java:536)
at zf.test.ZFAssetTest.TC15ExecuteActionWithoutParamater(ZFAssetTest.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC15ExecuteActionWithoutParamater -->
  <testcase name="TC17EditAssetstActions" time="263.652" classname="zf.test.ZFAssetTest">
    <failure type="java.lang.AssertionError" message="Expected value is : SUCCESS      Actual value is : Asset added successfully">
      <![CDATA[java.lang.AssertionError: Expected value is : SUCCESS      Actual value is : Asset added successfully
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.compareText(ExtentReport.java:156)
at zf.pages.ZFAssetPage.verifyToastermessage(ZFAssetPage.java:776)
at zf.pages.ZFAssetPage.editAssetstActions(ZFAssetPage.java:670)
at zf.test.ZFAssetTest.TC17EditAssetstActions(ZFAssetTest.java:113)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC17EditAssetstActions -->
  <testcase name="TC09CreateChildAssettWithAllFeilds" time="242.757" classname="zf.test.ZFAssetTest">
    <failure type="java.lang.AssertionError" message="TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - empty">
      <![CDATA[java.lang.AssertionError: TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - empty
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.elementCatch(ExtentReport.java:258)
at framework.ElementManager.elementClick(ElementManager.java:63)
at framework.ElementManager.waitElementVisibleClick(ElementManager.java:701)
at zf.pages.ZFAssetPage.createChildAssetWithAllFeilds(ZFAssetPage.java:706)
at zf.test.ZFAssetTest.TC09CreateChildAssettWithAllFeilds(ZFAssetTest.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC09CreateChildAssettWithAllFeilds -->
  <testcase name="TC13VerifyVehicleAssetstWithMandatoryAutopopulatedMetadataKeys" time="220.938" classname="zf.test.ZFAssetTest">
    <failure type="java.lang.AssertionError" message="TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - Element value is not retriving">
      <![CDATA[java.lang.AssertionError: TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - Element value is not retriving
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.elementCatch(ExtentReport.java:254)
at framework.ElementManager.elementGetValue(ElementManager.java:362)
at zf.pages.ZFAssetPage.verifyVehicleAssetstWithMandatoryAutopopulatedMetadataKeys(ZFAssetPage.java:446)
at zf.test.ZFAssetTest.TC13VerifyVehicleAssetstWithMandatoryAutopopulatedMetadataKeys(ZFAssetTest.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC13VerifyVehicleAssetstWithMandatoryAutopopulatedMetadataKeys -->
  <testcase name="TC14CreateAssetWithoutMandatoryInput" time="121.321" classname="zf.test.ZFAssetTest"/>
  <testcase name="TC03assetAdvancedSearch" time="138.417" classname="zf.test.ZFAssetTest"/>
  <testcase name="TC12FieldValidationsMandatoryFieldVin" time="234.975" classname="zf.test.ZFAssetTest">
    <failure type="java.lang.AssertionError" message="Expected value is : Failed      Actual value is : SUCCESS">
      <![CDATA[java.lang.AssertionError: Expected value is : Failed      Actual value is : SUCCESS
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.compareText(ExtentReport.java:156)
at zf.pages.ZFAssetPage.verifyToastermessage(ZFAssetPage.java:774)
at zf.pages.ZFAssetPage.fieldValidationsMandatoryFieldVin(ZFAssetPage.java:494)
at zf.test.ZFAssetTest.TC12FieldValidationsMandatoryFieldVin(ZFAssetTest.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC12FieldValidationsMandatoryFieldVin -->
  <testcase name="TC07CreateAssetstWithActions" time="260.662" classname="zf.test.ZFAssetTest">
    <failure type="java.lang.AssertionError" message="Expected value is : SUCCESS      Actual value is : Asset added successfully">
      <![CDATA[java.lang.AssertionError: Expected value is : SUCCESS      Actual value is : Asset added successfully
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.compareText(ExtentReport.java:156)
at zf.pages.ZFAssetPage.verifyToastermessage(ZFAssetPage.java:776)
at zf.pages.ZFAssetPage.CreateAssetstWithActions(ZFAssetPage.java:621)
at zf.test.ZFAssetTest.TC07CreateAssetstWithActions(ZFAssetTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC07CreateAssetstWithActions -->
  <testcase name="TC08editExistAssetDetails" time="127.305" classname="zf.test.ZFAssetTest"/>
  <testcase name="TC18VerifyAssetActionsUI" time="84.075" classname="zf.test.ZFAssetTest"/>
</testsuite> <!-- zf.test.ZFAssetTest -->
