<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="pcch-divyag" name="zf.test.ZFUserHomeTest" tests="4" failures="1" timestamp="21 Mar 2019 03:40:42 GMT" time="11.769" errors="0">
  <testcase name="Tc02editUser" time="0.000" classname="zf.test.ZFUserHomeTest">
    <skipped/>
  </testcase> <!-- Tc02editUser -->
  <testcase name="Tc01addUser" time="0.000" classname="zf.test.ZFUserHomeTest">
    <skipped/>
  </testcase> <!-- Tc01addUser -->
  <testcase name="Tc03DeleteUser" time="0.000" classname="zf.test.ZFUserHomeTest">
    <skipped/>
  </testcase> <!-- Tc03DeleteUser -->
  <testcase name="beforeMethod" time="11.769" classname="zf.test.ZFUserHomeTest">
    <failure type="java.lang.AssertionError" message="TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - Element not found">
      <![CDATA[java.lang.AssertionError: TIMEOUT EXCEPTION element does not exist after waiting 90 seconds - Element not found
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.elementCatch(ExtentReport.java:245)
at framework.ElementManager.elementSendKeys(ElementManager.java:121)
at zf.pages.MicrosoftLoginPage.microsoftLogin(MicrosoftLoginPage.java:20)
at zf.test.ZFUserHomeTest.beforeMethod(ZFUserHomeTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- beforeMethod -->
</testsuite> <!-- zf.test.ZFUserHomeTest -->
